template: true   # required for local templates.
valuesFilePath: ./values.yml

resources:
  - name: myFirstRepo
    type: GitRepo
    configuration:
      # SCM integration where the repository is located
      gitProvider: {{ .Values.myRepo.gitProvider }} # this will be replaced from values.yml
      # Repository path, including org name/repo name
      path: {{ .Values.myRepo.path }} # this will be replaced from values.yml
      branches:
        # Specifies which branches will trigger dependent steps
        include: master

  - name: cron_trigger
    type: CronTrigger
    configuration:
      interval: '*/5 * * * *'     # Every 5 minutes

pipelines:          
  - name: Use_The_CLI
    configuration:
      jfrogCliVersion: 2
    steps:
#Ping instances
      - name: Ping_psemea
        type: Bash
        configuration:
          inputResources:
            # Sets up step to be triggered when there are commit events to myFirstRepo
            - name: myFirstRepo
          integrations:
            - name: token_pseme
        execution:
          onStart:
            - configure_jfrog_cli --artifactory-url ${int_token_pseme_url}/artifactory --access-token ${int_token_pseme_accessToken} --server-name psemea
          onExecute:
            - jf rt ping pseme

      - name: Ping_fabienl
        type: Bash
        configuration:
          inputResources:
            # Sets up step to be triggered when there are commit events to myFirstRepo
            - name: myFirstRepo
          integrations:
            - name: token_fabienl
        execution:
          onStart:
            - configure_jfrog_cli --artifactory-url ${int_token_fabienl_url}/artifactory --access-token ${int_token_fabienl_accessToken} --server-name fabienl
          onExecute:
            - jf rt ping fabienl
#Download the plugin

#Execute the plugin
      - name: test_cli
        type: Bash
        configuration:
	        inputSteps:
            - name: Ping_psemea
            - name: Ping_fabienl
          inputResources:
            # Sets up step to be triggered when there are commit events to myFirstRepo
            - name: myFirstRepo
          integrations:
            - name: token_fabienl
            - name: token_pseme
        execution:
          onStart:
            - configure_jfrog_cli --artifactory-url ${int_token_fabienl_url}/artifactory --access-token ${int_token_fabienl_accessToken} --server-name fabienl
            - configure_jfrog_cli --artifactory-url ${int_token_pseme_url}/artifactory --access-token ${int_token_pseme_accessToken} --server-name psemea
            - jf c s
            - jf -v
            - jf rt dl Repo_diff_plugin/repo-diff --flat --server-id fabienl || true
            - chmod +x repo-diff
            - ./repo-diff diff create local fabienl psemea 
            - mkdir -p /root/.jfrog/plugins/repo-diff/bin
            - cp repo-diff /root/.jfrog/plugins/repo-diff/bin/repo-diff 
            - jf repo-diff 
          onExecute:
            - jf repo-diff diff create local psemea fabienl
            - ls -all
