template: true   # required for local templates.
valuesFilePath: ./values.yml

resources:
  - name: myFirstRepo
    type: GitRepo
    configuration:
      # SCM integration where the repository is located
      gitProvider: {{ .Values.myRepo.gitProvider }} # this will be replaced from values.yml
      # Repository path, including org name/repo name
      path: {{ .Values.myRepo.path }} # this will be replaced from values.yml
      branches:
        # Specifies which branches will trigger dependent steps
        include: master

  - name: cron_trigger
    type: CronTrigger
    configuration:
      interval: '*/5 * * * *'     # Every 5 minute


pipelines:          
  - name: Use_The_CLI
    steps:
      - name: test_cli
        type: Bash
        configuration:
          inputResources:
            # Sets up step to be triggered when there are commit events to myFirstRepo
            - name: myFirstRepo
          integrations:
            - name: token_fabienl
            - name: token_psemea
        execution:
          onStart:
            - configure_jfrog_cli --artifactory-url ${int_token_fabienl_url}/artifactory --access-token ${int_token_fabienl_accessToken} --server-name fabienl
            - configure_jfrog_cli --artifactory-url ${int_token_psemea_url}/artifactory --access-token ${int_token_psemea_accessToken} --server-name psemea
            - jfrog c s
            - jfrog rt dl Repo_diff_plugin/repo-diff --flat --server-id fabienl
            - mkdir -p /tmp/.jfrog/plugins/repo-diff/bin
            - cp repo-diff /tmp/.jfrog/plugins/repo-diff/bin/repo-diff 
            - jfrog repo-diff psemea fabienl
          onExecute:
            # Data from input resources is available as env variables in the step
            - chmod +x repodiff
            #- ./repodiff diff create local fabienl psemea
            - ls -all
