template: true   # required for local templates.
valuesFilePath: ./values.yml

resources:
  - name: myFirstRepo
    type: GitRepo
    configuration:
      # SCM integration where the repository is located
      gitProvider: {{ .Values.myRepo.gitProvider }} # this will be replaced from values.yml
      # Repository path, including org name/repo name
      path: {{ .Values.myRepo.path }} # this will be replaced from values.yml
      branches:
        # Specifies which branches will trigger dependent steps
        include: master

  - name: cron_trigger
    type: CronTrigger
    configuration:
      interval: '*/5 * * * *'     # Every 5 minute


pipelines:          
  - name: Use_The_CLI
    steps:
      - name: test_cli
        type: Bash
        configuration:
          inputResources:
            # Sets up step to be triggered when there are commit events to myFirstRepo
            - name: 
              - myFirstRepo
              - token_psemea
              - token_fabienl
        execution:
          onStart:
            - configure_jfrog_cli --artifactory-url https://fabienl.jfrog.io/artifactory --user fabienl@jfrog.com --access-token int_token_fabienl_token_fabienl --server-name fabienl
            - configure_jfrog_cli --artifactory-url https://psemea.jfrog.io/artifactory --user fabienl@jfrog.com --access-token int_token_psemea_token_psemea --server-name psemea
            - jfrog c s
            - jfrog rt dl Repo_diff_plugin/repo-diff --flat --server-id fabienl
            - cp repo-diff $HOME/.jfrog/plugins/repo-diff/bin/repo-diff 
            - jfrog repo-diff psemea fabienl
          onExecute:
            # Data from input resources is available as env variables in the step
            - chmod +x repodiff
            #- ./repodiff diff create local fabienl psemea
            - ls -all
